version: '3.4'

services:
  elastica:
    build: .
    container_name: elastica
    environment:
      - ES_HOST=elasticsearch
      - PROXY_HOST=nginx
    networks:
      - esnet

  elasticsearch7_1:
    build: ./env/elasticsearch/
    container_name: elasticsearch
    privileged: true
    environment:
      - bootstrap.memory_lock=true
      - network.host=10.10.10.15
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      esnet:
        ipv4_address: 10.10.10.15
  elasticsearch7_2:
    build: ./env/elasticsearch/
    privileged: true
    environment:
      - bootstrap.memory_lock=true
      - network.host=10.10.10.16
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      esnet:
        ipv4_address: 10.10.10.16

  nginx:
    build: ./env/nginx/
    networks:
      esnet:
        ipv4_address: 10.10.10.5


volumes:
  esdata1:
    driver: local
  esdata6_1:
    driver: local

networks:
  esnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.10.10.0/24
