elastica:
  #build: . # In case the image must be built locally
  image: ruflin/elastica
  ports:
    - "9200:9200"
  volumes:
    - .:/app
  links:
    - nginx
    - elasticsearch
  environment:
    - ES_HOST=elasticsearch
    - PROXY_HOST=nginx
elasticsearch:
#  build: ./env/elasticsearch/  # In case image must be built locally
  image: ruflin/elasticsearch-elastica
nginx:
  image: nginx
  volumes:
    - ./env/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./env/nginx/mime.types:/etc/nginx/mime.types
  ports:
    - "12345"
    - "12346"
    - "80"
  links:
    - elasticsearch
