elastica:
  build: .
  #image: ruflin/elastica
  ports:
    - "9200:9200"
  links:
    - nginx
    - elasticsearch
  environment:
    - ES_HOST=elasticsearch
    - PROXY_HOST=nginx
elasticsearch:
  build: ./env/elasticsearch/
  #image: ruflin/elasticsearch-elastica
  volumes_from:
    - data
nginx:
  build: ./env/nginx/
  #image: ruflin/nginx-elastica
  links:
    - elasticsearch
# data container to share data between elasticsearch nodes for snapshot testing
data:
  image: ruflin/elastica-data
  volumes:
    - "/tmp/backups/backup1"
    - "/tmp/backups/backup2"
