---

- name: Create a virtual machine
  connection: local
  hosts: localhost
  sudo: true
  vars:
    - ES_VER: "2.0.0~beta2"
    - ES_SHORT_VER: "2.0"
    # - ES_MAPPER_ATTACHMENTS_VER: "2.7.0"
    # - ES_TRANSPORT_MEMCACHED_VER: "2.7.0"
    # - ES_TRANSPORT_THRIFT_VER: "2.7.0"
    # - ES_GEOCLUSTER_FACET_VER: "0.0.12"
    # - ES_IMAGE_PLUGIN_VER: "1.7.1"
    - ES_PROJECT_ROOT: "{{ lookup('env', 'ES_PROJECT_ROOT') }}"
  roles:
    - elasticsearch
    - nginx
    - php
